### ISSUE TITLE
Feature: Add CI to generate latest build PDF

### ISSUE THREAD

**Issue by tanhauhau** [Andyccs/CZ4013-distributed-system-summary#3]
[ShareLatex CI](https://www.sharelatex.com/github/) or Travis CI.
And 'latest pdf build badge' for README.

**Comment by Andyccs** [comment]
I have added that, however, the badge does not show correct images every time.

**Comment by tanhauhau** [comment]
Did you realise that the ShareLatex build somehow has error and only generated 5 pages of pdf?

**Comment by Andyccs** [comment]
No I don't, fixing now

**Comment by Andyccs** [comment]
fix in b37a63d879652456aa775f0281140c136a598f1e and a8f35c8630b4736eaff877bd3d16cb17e7c15efe
